create: nightly.yml
SpringProject24/FoodieTree pull request #8
Opened 2024-06-16 04:52 UTC by hoseong511

## 개요

nightly build 깃허브 actions 추가 

## PR 유형
어떤 변경 사항이 있나요?

- [ ] 새로운 기능 추가
- [ ] 버그 수정
- [ ] CSS 등 사용자 UI 디자인 변경
- [ ] 코드에 영향을 주지 않는 변경사항(오타 수정, 탭 사이즈 변경, 변수명 변경)
- [ ] 코드 리팩토링
- [ ] 주석 추가 및 수정
- [ ] 문서 수정
- [ ] 테스트 추가, 테스트 리팩토링
- [x] 빌드 부분 혹은 패키지 매니저 수정
- [ ] 파일 혹은 폴더명 수정
- [ ] 파일 혹은 폴더 삭제

## 작업사항
- 스케쥴 "0 10 * * 1-5" # 월요일 - 금요일 10:00 UTC, 18:00 KST 작업 설정

## 변경로직

2024-06-17 09:39 UTC, munginisfree reviewed
고생하셨습니다~

2024-06-17 09:39 UTC, munginisfree commented on .github/workflows/nightly.yml
> +  dependency-submission:
좋습니다

2024-06-17 09:40 UTC, munginisfree approved these changes

2024-06-17 09:40 UTC, munginisfree commented on .github/workflows/nightly.yml
> +name: Nightly build
굿~

2024-06-17 09:42 UTC, munginisfree requested changes
comment

2024-06-17 09:43 UTC, munginisfree approved these changes
굿

2024-06-18 07:28 UTC, eeungji approved these changes
굿~

2024-06-18 07:40 UTC, merged